scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: ['spring-boot-application:8888']
  
  - job_name: 'tempo'
    scrape_interval: 15s
    static_configs:
      - targets: ['tempo:3200']
